name: Publish Docker image

on:
  push:
    tags:
      - '**'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Extract Tag
        id: get_tag_name
        run: |
          echo "IMAGE_VERSION=${GITHUB_REF/refs\/tags\//}" >> ${GITHUB_ENV}

      - name: Test
        run: |
          echo $IMAGE_VERSION

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $IMAGE_VERSION
