name: Publish Docker image

on:
  push:
    tags:
      - '**'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          repository: inshur/fy
          tag_with_ref: true
