name: Publish Docker image

on:
  push:
    tags:
      - '**'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Extract Tags
        run: |
          #TAGS="ghcr.io/${{ github.repository }}:${{ github.sha }}"
          #if [[ $GITHUB_REF == ref/head/master ]]; then
          #  TAGS="$TAGS,ghcr.io/${{ github.repository }}:latest"
          #fi

          IMAGE_VERSION="${GITHUB_REF/refs\/tags\//}"
          TAGS="ghcr.io/inshur/fy:$IMAGE_VERSION"
          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
          echo $TAGS

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/inshur/fy:1.0.2
