name: Publish Test Docker image

on:
  push:
    tags:
      - '**'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tags
        id: tags
        run: |
          IMAGE_VERSION="${GITHUB_REF/refs\/tags\//}"
          TAGS="ghcr.io/inshur/fy-test:$IMAGE_VERSION"
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> "$GITHUB_ENV"
          echo "TAGS=${TAGS}" >> "$GITHUB_ENV"
          echo "$TAGS"
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

      - name: Check out repo
        uses: actions/checkout@v4.1.6

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          # failing to use a variable here for some reason:
          # Error: buildx call failed with: invalid tag "${TAGS}": invalid reference format
          #tags: inshur/fy:latest
          tags: ${{ steps.tags.outputs.tags }}

